.gitignore, docs/source/usage.rst, wayback/_client.py, wayback/exceptions.py, wayback/tests/test_client.py
Move all our exception classes to `wayback.exceptions` and document them so they can easily be used.
This seems like a fairly common pattern in the Python packaging world, but if there’s a better way to structure our exceptions for both internal *and* external use, I’m happy to adjust! Also open to renaming this module and the base exception to `error` or whatever else while we are cleaning up exception-y things.
=> Expose and document exception classes

requirements.txt, wayback/_utils.py, wayback/exceptions.py
We had a whole bunch of vestigial bits in the `_utils` module that were left over from web-monitoring-processing but not used here. This removes them and also removes the `lxml` dependency, which was only present because of a vestigial utility function.
While I was at it, I also moved the `SessionClosedError` class to the `exceptions` module, since I completely missed it in #7.
=> Remove vestigial bits from `_utils` module

wayback/_client.py
Renames the default user-agent name to `wayback/{version} (+https://github.com/edgi-govdata-archiving/wayback)`, since the old one doesn’t make as much sense in this more generic module.
Fixes #11.
*(NOTE: web-monitoring-processing will need to start setting a custom user-agent now.)*
=> Change Default User-Agent String

wayback/_client.py
The response would evenutally be closed by garbage collection, but it is
better to close it explicitly. When requests are issued at a high rate,
this makes a significant difference.
=> Explicitly close response when search is done.

wayback/_client.py
When we handle memento redirects, we should have been loading all the content and then closing the response so that the connection is released for re-use, otherwise it just gets left hanging around :(
This contributes to solving some of the issues over in edgi-govdata-archiving/web-monitoring-processing#525
=> Release connections for memento redirects

wayback/_client.py
This is a bit of a follow-on to #19 and #20.
These are all the remaining places I could find possible connection leaks from responses being held onto. A lot of these cases *should* be covered by the requests library (it takes a similar approach and caches response bodies before raising most exceptions), but I didn't feel like I could be certain that was always true, so I went with the most cautious approach: anywhere we aren't explicitly returning an open request, read/cache the body and close it.
=> Make sure to close responses where they may leak

docs/source/release-history.rst
@danielballan do these read OK? I feel like the connection fixes we implemented are working well, and demand a release at this point. (The crazy proposal in #23 seems big enough and speculative enough to be worth a separate release.)
If this looks good, I was thinking I’d cut a release straightaway (Thursday, Feb. 13th).
=> Add final release notes for v0.2.2

.circleci/config.yml, setup.py
This commit relaxes the setup.py to allow for python 3.6, which still passes the test suite. I also took a shot at updating the circleci setup to test 3.6, but I'm not 100% sure I did that correctly or that it works.
Fixes #27
=> Support Python 3.6

docs/source/_static/css/custom.css, docs/source/conf.py
Makes the parameter names in our docs readable again my adding a colon between the parameter names and types. The fix here is really exactly the same as edgi-govdata-archiving/web-monitoring-processing#489.
Fixes #16.
=> Add colon between parameter names & types in docs

README.rst
Pretty much just what it says: updates the documentation link(s) in the README to point to readthedocs.org.
=> Update docs links in README to use readthedocs

docs/source/release-history.rst, wayback/_client.py, wayback/tests/test_client.py
A memento’s `history` attribute now only lists the redirects that were mementos (i.e. redirects that would have been seen when browsing the recorded site at the time it was recorded). Other redirects involved in working with the memento API are still available in `debug_history`, which includes all redirects, whether they were mementos or not.
Fixes #36.
=> Only include mementos in `history`

docs/source/release-history.rst, wayback/_client.py, wayback/tests/cassettes/test_search_does_not_repeat_results, wayback/tests/test_client.py
The CDX API sometimes returns repeat results (most likely because save-page-now is being so heavily used that two copies were really being saved at the same time, but we have not been able to get a clear answer on causes from the Wayback team yet). Since there's no useful way to get information about the two mementos with identical CDX records (assuming there actually are two, and there's not a CDX problem), this simply filters out the repeats so users don't have to worry about handling them properly.
Fixes #40.
=> Filter out repeat results from `WaybackClient.search`

docs/source/release-history.rst, wayback/_client.py, wayback/tests/test_client.py
This is a breaking API change, but is intended to make our output data more clear. Fixes #39.
=> Include tzinfo in CDX search results

.circleci/config.yml
We were using YAML anchors and references to run tests against multiple Python versions, but CircleCI recently added a specialized “matrix” syntax for doing this kind of thing in a nicer and more powerful way. This updates to that new syntax.
=> Use CircleCI matrix configuration syntax

docs/source/release-history.rst, docs/source/usage.rst, wayback/_client.py, wayback/exceptions.py, wayback/tests/test_client.py
Status code 429 ("Too Many Requests") specifies that you've hit a rate limit, and the Wayback Machine makes good use of it. We now raise a special error type for this case since it's something a user might want to have special handling for.
Fixes #22.
=> Raise `RateLimitError` for 429 responses

.circleci/config.yml, docs/source/release-history.rst, wayback/_client.py, wayback/exceptions.py, wayback/tests/cassettes/test_get_memento_raises_blocked_error, wayback/tests/cassettes/test_search_raises_for_blocked_urls, wayback/tests/test_client.py
Searching for a blocked URL used to raise a relatively uninformative and generic `WaybackException` error. Getting a memento of a blocked URL likewise raised a generic `MementoPlaybackError`. Now both situations raise a `BlockedSiteError` that more clearly describes the situation.
Fixes #34.
=> Add `BlockedSiteError` for URLs that are blocked

.circleci/config.yml, docs/source/index.rst, requirements-dev.txt
We currently have one massive job for all the checks we do on a PR, which a) prevents us from seeing all the errors (since it stops at the first error) and b) means we execute things like linting and docs once for each Python version, when they really only need to run once (unlike tests). This splits the jobs into:
- test (runs tests and coverage)
- lint
- build (this is new! Builds and checks the package)
- docs (doesn't actually run, since we really build our docs on Travis. No reason to waste the effort in Circle.)
=> Split CircleCI work into several jobs

CONTRIBUTING.rst, README.rst, docs/source/index.rst, docs/source/installation.rst
This expands the description of the package and contrasts it with “internetarchive,” which this package might otherwise seem duplicative of. I’ve also tried to make a few other docs improvements while I was at it:
- Fix the build badge to point at Circle instead of Travis (since we aren’t building anything on Travis)
- Add some other appropriate badges.
- Add EDGI code of conduct links and info.
- Add some basic instructions to the README.
If you have a moment, would you mind taking a look, especially about the bits contrasting with the internetarchive package, @danielballan?
Fixes #13.
=> Improve docs and contrast with “internetarchive” package

docs/source/release-history.rst, wayback/_client.py, wayback/tests/cassettes/test_get_memento_raises_when_memento_is_outside_target_window, wayback/tests/cassettes/test_get_memento_target_window, wayback/tests/test_client.py
The `target_window` parameter for `get_memento()` is supposed to limit how far off in time from the requested time you can get a memento for when the `exact` parameter is `False`. However, it only works correctly when the target is off by less than a day! (The scenarios we were originally concerned with in EDGI almost invariably were on the scale of a few hours, so I guess that's how this error snuck in. 😬) If you set `exact=True` (the default), this bug wouldn’t be triggered.
We were checking the target offset by the number of seconds, irrespective of the additional number of days involved. We should have been checking by `total_seconds`, which converts the days into seconds and includes them. I’ve also added tests here to make sure this problem doesn’t occur again.
This PR targets the …
=> Fix `target_window` when redirect is > 1 day

docs/source/release-history.rst, docs/source/usage.rst, wayback/__init__.py, wayback/_client.py, wayback/_models.py, wayback/_utils.py, wayback/tests/test_client.py, wayback/tests/test_files/fws-gov-birds.txt, wayback/tests/test_utils.py
Rather than returning a requests.Response object from `WaybackClient.get_memento()`, we now return a completely new `Memento` type. It’s similar to requests.Response in a lot of ways, but it contains additional properties that are specific to mementos (like a timestamp) and has different values that reflect the historical archive rather than the exact response the Wayback Machine sent (e.g. `url` is the URL of the archived page, not `http://web.archive.org/web/<date>/<url>`; `headers` contains only the historic headers, not additional info added by the Wayback Machine).
There are two major reasons for this:
1. We can provide some more useful conveniences like the above noted bits.
2. We can change the underlying HTTP implementation, since we no longer expose it publicly. This is critical …
=> Return a new `Memento` type from `get_memento()`

docs/source/release-history.rst, wayback/_client.py, wayback/_models.py, wayback/tests/cassettes/test_get_memento_with_path_based_redirects, wayback/tests/test_client.py
Most redirects in Wayback redirect to a complete URL, with headers like:
Location: http://web.archive.org/web/20201027215555id_/https://www.whitehouse.gov/administration/eop/ostp/about/student/faqs
But some include only an absolute path, (which is still valid) e.g:
Location: /web/20201027215555id_/https://www.whitehouse.gov/ostp/about/student/faqs
We weren't correctly handling the latter case, leading to exceptions while parsing headers.
Fixes #59.
=> Handle `Location` headers that are absolute paths

wayback/_models.py, wayback/tests/cassettes/test_get_memento_with_schemeless_redirects, wayback/tests/test_client.py
In #60, we fixed an issue where redirects were path-based, but didn't handle redirects that were schemeless (i.e. they have a host but no scheme). Rather than adding more logic for this, I remembered Python has a built in method -- `urljoin()` -- for resolving relative URLs that handles both these cases (and probably a few others, like non-absolute paths). We should have used it in the first place!
=> Handle schemeless URLs in `Location` header

docs/source/release-history.rst, wayback/_client.py, wayback/tests/test_client.py
Backport the fix for the `timeout` bug in #68 to the v0.2.x release line, since it's a pretty critical issue.
=> Backport session timeout fix from #68

wayback/_client.py
In #68, we forgot to update the documentation to specify the new default value.
=> Correct documentation about new timeout default

wayback/_client.py, wayback/_utils.py, wayback/tests/test_client.py, wayback/tests/test_files/bad_timestamp_cdx.txt
* Currently there is a bug that prevents the parsing of CdxRecord when the timestamp is invalid, for example "20000800241623". This timestamp doesn't really make sense because the day is 00 and the hour is 24.
* The following code has the following error:
```python
import wayback
client = wayback.WaybackClient()
records = client.search("www.usatoday.com/*", matchType="domain", filter_field="statuscode:200")
len(list(records))
```
```python
wayback.exceptions.UnexpectedResponseFormat: Could not parse CDX output: "com,usatoday)/2000/century/tech/004.htm 20000800241623 http://www.usatoday.com:80/2000/century/tech/004.htm text/html 200 PAJWSPCRQMVBTYWV4NPJPNDQHKWJC3OO 6177" (query: {'url': 'www.usatoday.com/*', 'matchType': 'domain', 'filter': 'statuscode:200', 'showResumeKey': 'true', …
```
=> Fix bad timestamps

.circleci/config.yml
There have been some major releases to Python and we haven’t been testing on them!
=> Add Python 3.9 and 3.10 to the test matrix

.circleci/config.yml, .readthedocs.yml, LICENSE, README.rst, docs/requirements.txt, docs/source/_static/styles.css, docs/source/conf.py, requirements-dev.txt, requirements-docs.txt, wayback/_client.py, wayback/_utils.py
This takes over for #90 and sets appropriate, working constraints on all the dev dependencies involved in building docs (we should really set constraints on *all* the dev dependencies, but this is at least an improvement). I should get the docs building correctly again, and also takes advantage of new features in the docs tools we use (like a new recommended syntax for defaults in numpydoc!).
=> Repair docs build

docs/source/release-history.rst, wayback/_utils.py, wayback/tests/test_client.py, wayback/tests/test_files/bad_timestamp_cdx.txt
This commit extends the existing logic for handling invalid days of `00` to months that are `00`. It also adds a warning to be logged in both situations.
So if a timestamp of `20200001120000` will get rewritten to `20200112000000` prior to conversion to a datetime.
I have tested on live CDX API data that was failing, and this fix causes the full result to be returned. If more information is known about why this approach is taken it would be good to add in a comment?
Closes #88
=> Correct CDX API timestamps with month of 00

wayback/_utils.py
I had wondered before about the performance implications of making an extra list when parsing timestamps, and @edsu’s recent patch in #89 got me to take a look.
This is a minor 5-6% performance improvement, which may be worthwhile if you are iterating through extremely large result sets. Part of this is not allocating a few new lists, and part is checking the least significant digit first, since there are relatively few valid months/days where the least significant digit is `0`.
Tested against a set of 1,000,000 randomly generated timestamps:
```py
from random import randint
def make_random_timestamp():
year = randint(1995, 2022)
month = randint(1, 12)
day = randint(1, 28)
hour = randint(0, 23)
minute = randint(0, 59)
second = randint(0, 59)
shuffle = randint(0, 3)
if shuffle == 0:
return …
```
=> Minor performance improvement to timestamp fix

.circleci/config.yml, .readthedocs.yml
Python 3.11 has been released! (We probably should have done this while it was in beta, but ¯\\\_(ツ)\_/¯)
=> Add Python 3.11 to the test matrix

wayback/_client.py
A while back, we added an actual `Memento` type to represent mementos retrieved via `get_memento()`. However, it looks like the return type for `get_memento()` in the docs wasn't updated.
=> Fix return type for `get_memento()` in docs

setup.py
PyPI has a whole list of URL types that it treats specially, and this makes use of some of them. Fixes #63.
=> Add project links to PyPI

docs/source/release-history.rst, wayback/_models.py, wayback/_utils.py, wayback/tests/cassettes/test_get_memento, wayback/tests/test_client.py
This fixes #98, which was caused by two changes:
1. The Internet Archive now returns most *archived* header names (i.e. those prefixed with `'x-archive-org-'`) in lower-case.
2. In HTTP/2 (now possible since we are using HTTPS as of #97), *all* headers are lower-case/case-insensitive.
Since that means it’s possible to wind up with different header name casing when running the same code on different systems, I had to go ahead and make the `Memento.headers` attribute case-insensitive (we probably should have done this long ago for user friendliness anyway). I've implemented that using code largely taken from Requests, since their implementation is not public so we can't just use it directly (plus we plan to switch of Requests at some point anyway). If we wind up switching to HTTPX, they …
=> Handle inconsistent header case for Mementos

docs/source/conf.py
The locations for the various Intersphinx mappings we use have changed, and the current configuration logs several warnings. This updates to the latest correct URLs.
=> Docs: Update Intersphinx mappings

docs/source/release-history.rst, wayback/_client.py, wayback/tests/test_client.py
This renames the `datetime` parameter of the `get_memento()` method to `timestamp`, which makes it consistent with the attribute names in `Memento` and `CdxRecord`. It's not a strictly necessary breaking change, but as long as we are making breaking changes to `search()` parameters, this is as good a time as any to do it.
=> Rename `datetime` parameter of `get_memento`

docs/source/release-history.rst, wayback/_client.py
In #94 and #102, we renamed several method parameters. This brings back the old names, but with deprecation warnings. We'll remove them fully in v0.5.0.
This does *not* support parameters that were completely *removed*, though. I did a search on GitHub, and it doesn't look like anybody is actually using them, so it didn't seem worth keeping support for them.
=> Deprecate instead of remove renamed parameters

docs/source/release-history.rst, wayback/_client.py, wayback/_models.py, wayback/tests/cassettes/test_get_memento_returns_memento_with_accurate_url, wayback/tests/test_client.py
This fixes an issue where the `Memento.url` property could be slightly incorrect, since it was based on the URL you requested the memento from (e.g. `https://web.archive.org/web/20221010000000/<url>`), rather than the actual URL the memento was captured from. The URL the memento is requested from matches records via SURT key rather than the URL.
For example, requesting an archived copy of `http://fws.gov/` might return a capture of `https://www.fws.gov/` instead. The returned Memento object’s `url` property used to be `http://fws.gov/` in this case, but this changes it to be `https://www.fws.gov/`.
Fixes #99.
=> Use the `Link` header to get a memento’s URL

docs/source/release-history.rst, wayback/_client.py, wayback/_models.py, wayback/_utils.py, wayback/tests/test_client.py
The `links` attribute on a Memento object links to other related resources, such as the first/previous/next/last memento of the current memento's URL. These are super useful for iterating and navigating through mementos, BUT the archive.org servers always return these as links to the memento in "view" mode. Users of this library rarely use "view" mode, and if you are iterating through links in a different mode, simply following one of the links can lead to subtle mistakes! To mitigate this, we now change all the links that reference mementos to use the same mode as the `Memento` object they are attached to.
Fixes #111.
=> Ensure memento's links match memento's mode

requirements.txt
Right now, this package is not compatible with urllib3 v2, so we need to set version constraints so package managers don’t try to install an incompatible version.
Partially covers #116.
=> Prevent installation with urllib3 v2

.circleci/config.yml, requirements-dev.txt, requirements-test.txt, setup.py
Earlier versions of flake8 do not support Python 3.12. Part of #123.
=> Upgrade Flake8 to v6.1.0

.circleci/config.yml, requirements-test.txt
This currently adds tests for Python 3.12.0 pre-releases (at the time of writing: 3.12.0rc3). It looks like there are some remaining issues to iron out in order to totally solve #123.
=> Support Python 3.12 Prereleases

docs/source/release-history.rst
We need an alpha release to test on Python 3.12.0rc3.
=> Prepare to release v0.4.3a1

docs/source/release-history.rst, wayback/_client.py, wayback/tests/cassettes/test_search_with_filter, wayback/tests/cassettes/test_search_with_filter_list, wayback/tests/cassettes/test_search_with_filter_tuple, wayback/tests/test_client.py
The `filter_field` parameter for `WaybackClient.search()` can now be a list or tuple of strings, letting you add multiple filters. For example, to search for all captures at `nasa.gov` with a 404 status and “feature” somewhere in the URL:
```python
client.search('nasa.gov/',
match_type='prefix',
from_date=date(2022, 1, 1),
to_date=date(2022, 2, 1),
filter_field=['statuscode:404',
'urlkey:.*feature.*'])
```
Thanks to @BilibalaX for starting this in #120.
=> Support multiple filters in CDX search

.circleci/config.yml
The production release of Python 3.12.0 is now available, so we should be testing with it instead of a pre-release. It’ll probably be a while before it’s available as an official CircleCI image though, so this is a little hacky. :(
=> Update CI to use Python 3.12.0

.circleci/config.yml, .github/dependabot.yml, .readthedocs.yml, setup.py
My understanding (we'll see, might be wrong!) is that dependabot will include `extras_require` entries as dev dependencies, so I've made deps installable that way (really that should have been done long ago): `pip install wayback[dev,test,docs]`.
=> Add Dependabot for dev dependencies

requirements-docs.txt
Now that Sphinx 7 and the various Sphinx themes and plugins we use all work correctly together, we should update all the docs tools. This includes some security fixes, useful bugfixes, and some new features I want to use (`maximum_signature_line_length` in Sphinx looks useful).
=> Update docs dependencies

.circleci/config.yml
CircleCI finally released an official image for Python 3.12 today, so we can switch over to that instead of my pre-release testing images.
=> Use official CircleCI image for Python 3.12

wayback/_client.py, wayback/_utils.py, wayback/tests/test_client.py
=> Lower search calls per second to 1

wayback/_client.py, wayback/_utils.py
To help diagnose when things are going wrong this commit adds some additional debug logging when requests are happening, what parameters are being used, sleep behavior and error responses from web.archive.org.
Closes #138
=> More debug logging

docs/source/release-history.rst, wayback/_client.py, wayback/_utils.py, wayback/exceptions.py, wayback/tests/test_utils.py
This adds a bunch of little tweaks related to the recent rate limit work. It should be more-or-less ready for release after this.
**The main thing** is adding a 60-second delay for 429 (rate limit) responses. Looking back at the docstring for the `RateLimitError` class, I think I might have originally *intended* to always raise instead of retry these, but git history shows it never actually worked that way. I want to get a patch release out with the new retry timings and logs, but patch release doesn’t seem like a good time change whether a response gets retried, so I’ve just made a longer delay here for now.
Then some other assorted bits and bobs:
- Downgrades the log level when we catch and retry exceptions (used to be WARN, now just INFO). The whole point of retry is to make this …
=> A little more rate limit tweaking for v0.4.4

.gitattributes
It turns out git has some neat language specific features it can enable if we tell it that `.py` files are Python code, e.g. https://calebhearth.com/git-method-history.
=> Tell git to treat `.py` files as Python

docs/source/release-history.rst, wayback/_client.py
We used to retry requests that got a response with a 429 status code (indicating that you've hit a rate limit on the server) automatically, but we've resolved that this is no longer a good approach.
See the discussion in https://github.com/edgi-govdata-archiving/wayback/issues/137#issuecomment-1828873225 for more detail, but the short version is that our previous retry behavior was specifically geared to a workflow EDGI used, and which had custom rate limits and other server behavior that most users won't have, and also helped to work around a bunch of deficiencies in our client-side rate limiting that were solved in the last release (but they do need [a *bit* more work](https://github.com/edgi-govdata-archiving/wayback/issues/137#issuecomment-1790980712) in this release, too). It turns …
=> Stop retrying after rate limit errors

.circleci/config.yml, docs/source/release-history.rst, docs/source/usage.rst, wayback/__init__.py, wayback/_client.py, wayback/_utils.py, wayback/tests/test_client.py, wayback/tests/test_utils.py
This significantly refactors how we manage rate limiting with the goal of making it more clear, flexible, and accurate going forward. It encompasses a few major changes:
The default limits are globally shared `RateLimit` objects, so multiple sessions without explicitly set limits will still coordinate their limiting together just like they used to.
Fixes #137.
Some of this also hopefully paves the way for an even bigger refactor of `WaybackSession` in #58.
=> Winter cleaning for rate limiting

.circleci/config.yml, .github/workflows/cd.yml
Precisely following https://learn.scientific-python.org/development/guides/gha-pure/
This introduces GHA, alongside CircleCI. An additional integration is not ideal, bu there are points in favor:
* GHA, being a GH-internal integration, is not a big jump to make.
* We can use this community-supported recipe as is.
* GHA can handshake directly with PyPI via [Trusted Publisher](https://docs.pypi.org/trusted-publishers/) that we do not need to handle secrets in the environment. (It seems like it ought to be possible to do this with CircleCI, but some cursory Googling did not turn anything up.)
=> Do PyPI release in GHA

src/wayback/_client.py, src/wayback/tests/cassettes/test_get_memento_works_on_archived_rate_limit_responses.yaml, src/wayback/tests/test_client.py
A memento can be a archive of an old rate limit error (status code 429) and in our feverish run to handle rate limit errors better at the end of 2023, we caused `WaybackSession.send()` to raise exceptions for both real rate limits *and* archived ones. However, the archived ones might be an actual memento that you were looking for, and should have been exempted from raising.
This solves the issue by simply checking whether a response is a memento and returning it immediately without doing any other checks, since the *effective* status code for a memento is always 200. (Checking various attributes of a memento is complicated, so it’s better to just return them right away rather than remembering to make complex exceptions in all the places where various response attributes have to be treated …
=> Don't raise on *archived* rate limit errors

.git_archival.txt
It turns out the way we populated the `ref-names` field causes its value to change depending on whether the commit a Git archive was built from was the head of a branch when it was built (which is often true when we first cut a release, but ceases to be true soon afterward. If someone downloads an archive *later* and tries to compare its signature with the one we released, it won’t match because this field has changed, and that’s a significant issue.
Unfortunately, there’s no good alternative that resolves this issue, so the best solution is to just remove the field. On the up-side, `describe-name` carries the more critical info about the the current tag or release version, so this isn’t a huge loss.
Thanks to @webknjaz for pointing this out: …
=> Remove `ref-names` field from `git_archival.txt`

.circleci/config.yml
Update tests to run on Python 3.13.0rc1, which has now been released.
=> Run tests on Python 3.13.0rc1

.circleci/config.yml
Somehow 3.13 never got added to the test matrix here after it was released. This adds it to the main matrix and adds 3.14.0rc2 (just out yesterday) to the pre-release matrix.
=> Add Python 3.13, 3.14rc to test matrix

.circleci/config.yml
Python 3.14.0 is now out, although Circle does not yet have an image, so this still uses an image from the pre-release Docker repo.
=> Test on production Python 3.14.0
